---
version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: chore
      include: scope
