#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

deploy() {
  local RED='\033[0;31m'
  local GREEN='\033[0;32m'
  local BLUE='\033[0;34m'
  local RESET='\033[0m'

  if [[ "${#}" -lt 1 ]]; then
    printf "%bUsage: deploy [PROJECT_NAME] [DOCKER-COMPOSE-FILE]%b" "${RED}" "${RESET}"

    return 1
  fi

  local PROJECT_NAME="${1}"
  local COMPOSE_FILE="${2:-docker-compose.yml}"

  printf "%bStarting services of %s%b\n" "${BLUE}" "${PROJECT_NAME}" "${RESET}"

  docker-compose -p "${PROJECT_NAME}" -f "${COMPOSE_FILE}" config -q
  docker-compose -p "${PROJECT_NAME}" -f "${COMPOSE_FILE}" pull -q
  docker-compose -p "${PROJECT_NAME}" -f "${COMPOSE_FILE}" up -d --remove-orphans

  printf "%bLogs for services of %s%b\n" "${BLUE}" "${PROJECT_NAME}" "${RESET}"

  docker-compose -p "${PROJECT_NAME}" -f "${COMPOSE_FILE}" logs

  printf "%bDeploy successful!%b\n" "${GREEN}" "${RESET}"
}

deploy "${@}"
