---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCRIPTS_NO_INTERACTIVE: "true"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Golang
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15"
      - run: |
          make
          git --no-pager diff -- ':(exclude)go.sum' && git diff --quiet -- ':(exclude)go.sum'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - run: |
          docker build --build-arg "APP_VERSION=$(make version)" -t "${{ secrets.DOCKER_USER }}/$(make name):$(make version)" .
          docker push "${{ secrets.DOCKER_USER }}/$(make name):$(make version)"
      - uses: codecov/codecov-action@v1

  publish:
    name: Publish
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          FLUX_TOKEN: ${{ secrets.FLUX_TOKEN }}
          FLUX_WEBHOOK_URL: ${{ secrets.FLUX_WEBHOOK_URL }}
        run: |
          curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/main/bootstrap" | bash -s "docker_promote"
          scripts/docker_promote "${{ secrets.DOCKER_USER }}/$(make name)" "$(make version)"
          curl --header "X-Signature: sha1=$(printf "{}" | openssl dgst -sha1 -hmac "${FLUX_TOKEN}")" --data "{}" "${FLUX_WEBHOOK_URL}"
      - name: GoReport
        run: |
          curl --disable --silent --show-error --location --max-time 30 -X POST https://goreportcard.com/checks?repo=github.com/${GITHUB_REPOSITORY}
